# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fermi.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66\x65rmi.proto\x12\x05\x66\x65rmi\"\xa0\x01\n\x0fGenerateRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x16\n\x0emax_new_tokens\x18\x03 \x01(\r\x12\x16\n\x0erepeat_penalty\x18\x04 \x01(\x02\x12\x15\n\rsystem_prompt\x18\x05 \x01(\t\x12\x13\n\x0btemperature\x18\x06 \x01(\x02\x12\r\n\x05top_p\x18\x07 \x01(\x02\"G\n\x10GenerateResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x10\n\x08token_id\x18\x02 \x01(\r\x12\x12\n\nsession_id\x18\x03 \x01(\t2F\n\x05\x46\x65rmi\x12=\n\x08Generate\x12\x16.fermi.GenerateRequest\x1a\x17.fermi.GenerateResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fermi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=23
  _globals['_GENERATEREQUEST']._serialized_end=183
  _globals['_GENERATERESPONSE']._serialized_start=185
  _globals['_GENERATERESPONSE']._serialized_end=256
  _globals['_FERMI']._serialized_start=258
  _globals['_FERMI']._serialized_end=328
# @@protoc_insertion_point(module_scope)
